### ISSUE TITLE
restart is not supported by particle_deterministic

### ISSUE THREAD

**Issue by MJomaba** [mrc-ide/mcstate#153]
Trying to use restart=TRUE with particle_deterministic leads to the following error:

Error in x$read() : 
  callr subprocess failed: 'save_restart' cannot be used with particle_deterministic
Type .Last.error.trace to see where the error occured 
22.
stop(cond) 
21.
callr:::throw(data$error) 
20.
x$read() 
19.
FUN(X[[i]], ...) 
18.
lapply(private$remotes[i], function(x) x$read()) 
17.
self$step() 
16.
obj$run() 
15.
pmcmc_multiple_parallel(pars, initial, filter, control) 
14.
mcstate::pmcmc(pars$mcmc, filter, initial = initial, control = control) at global_fit.R#6
13.
fit_run(pars, filter, control$pmcmc) at script.R#69
12.
eval(ei, envir) 
11.
eval(ei, envir) 
10.
withVisible(eval(ei, envir)) 
9.
source(private$recipe$script, local = private$envir, echo = echo, 
    max.deparse.length = Inf) 
8.
force(code) 
7.
withr::with_dir(private$workdir, {
    source(private$recipe$script, local = private$envir, echo = echo, 
        max.deparse.length = Inf)
}) 
6.
force(code) 
5.
withr::with_envvar(private$envvar, {
    withr::with_dir(private$workdir, {
        source(private$recipe$script, local = private$envir, 
            echo = echo, max.deparse.length = Inf) ... 
4.
self$run_execute(echo) 
3.
withCallingHandlers({
    self$run_prepare(message)
    private$fetch()
    self$run_execute(echo) ... 
2.
version$run(parameters, instance, envir, message, tags, echo, 
    use_draft, remote) 
1.
orderly::orderly_run("rtm_spim_fits", parameters = list(data_date = "2021-10-29", 
    region = "london", model_type = "BB", short_run = TRUE, deterministic = TRUE, 
    assumptions = "central"), use_draft = "newer")

**Comment by richfitz** [comment]
Fixed in #154
