### ISSUE TITLE
add initial_log_likelihood argument to particle filter

### ISSUE THREAD

**Issue by lwhittles** [mrc-ide/mcstate#185]
Allow the user to pass a function (`initial_log_likelihood`) to particle_filter$new(). The function `initial_log_likelihood` should take the transformed model parameters as an argument and return the a log likelihood component as a scalar, which is used to initialise the particle filter instead of zeros here:
https://github.com/mrc-ide/mcstate/blob/ba321514127deafdf98f889be7ac14f24b627816/R/particle_filter_state.R#L183.

This will allow joint fitting to non-time-series data (in addition to the time-series data used by the particle filter).
The data will be loaded into the `initial_log_likelihood` function rather than passed to the particle filter separately.

**Comment by richfitz** [comment]
Fixed in #186
