### ISSUE TITLE
test suite not robust to missing optional deps

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/mcstate#193]
both coda and odin.dust used unconditionally

**Comment by hillalex** [comment]
What's the appropriate pattern here; just to skip tests dependent on those packages if they aren't present? Looks like that happens with tests that depend on `mockery`.  Am a little confused as surely running tests always requires optional deps since `testthat` is itself optional?

**Comment by richfitz** [comment]
yeah, just literally adding `skip_if_not_installed("package")` on the blocks that use them. I think that the the environment variable I mentioned on the yt ticket can be used in conjunction with `R CMD check` (most easily via `rcmdcheck::rcmdcheck`) to simulate the packages not being available
