### ISSUE TITLE
Problem with mcstate chain parallelisation

### ISSUE THREAD

**Issue by AVicco** [mrc-ide/mcstate#211]
I have a problem with the chain parallelisation in mcstate and I was hoping you could kindly help me. I am currently following the vignette on mcstate parallelisation, but when I try it an error occurs. I have also included the relevant code to reproduce this error.

sir_generator <- odin.dust::odin_dust("IDX.R")
data <-read.csv(“data.csv”)
dt <- 0.25 
combined_data <- mcstate::particle_filter_data(data = data,
                                               time = "date",
                                               rate = 1 / dt,
                                               initial_time = 0)

n_particles <- 100
compare_function <- function(state, observed, pars = NULL) {
  exp_noise <- 1e6
  lambda <- state[3, , drop = TRUE] +
    [rexp](https://rdrr.io/r/stats/Exponential.html)(n = [length](https://rdrr.io/r/base/length.html)(state), rate = exp_noise)
  [dpois](https://rdrr.io/r/stats/Poisson.html)(x = observed$cases, lambda = lambda, log = TRUE)
}

filter <- mcstate::particle_filter$new(data = combined_data,
                                       model = sir_generator,
                                       n_particles = n_particles,
                                       compare = compare_function,
                                       seed = 1L,
                                       n_threads = 9)

beta <- mcstate::[pmcmc_parameter](https://mrc-ide.github.io/mcstate/reference/pmcmc_parameter.html)("beta", 0.2, min = 0)
gamma <- mcstate::[pmcmc_parameter](https://mrc-ide.github.io/mcstate/reference/pmcmc_parameter.html)("gamma", 0.1, min = 0, prior = function(p)
  [dgamma](https://rdrr.io/r/stats/GammaDist.html)(p, shape = 1, scale = 0.2, log = TRUE))

proposal_matrix <- [diag](https://rdrr.io/r/base/diag.html)(0.1, 2)

mcmc_pars <- mcstate::[pmcmc_parameters](https://mrc-ide.github.io/mcstate/reference/pmcmc_parameters.html)$new([list](https://rdrr.io/r/base/list.html)(beta = beta, gamma = gamma),
                                           proposal_matrix)
n_steps <- 10000
n_burnin <- 200
n_chains <- 3
n_steps_retain <- 1000
n_workers <- 3
n_threads_total <-9

control <- mcstate::pmcmc_control(
    n_steps,
    save_state = TRUE,
    save_trajectories = TRUE,
    progress = TRUE,
    n_chains = n_chains,
    n_burnin = n_burnin,
    n_steps_retain = n_steps_retain,
    n_workers = n_workers,
    n_threads_total = n_threads_total
  )
pmcmc_run <- mcstate::[pmcmc](https://mrc-ide.github.io/mcstate/reference/pmcmc.html)(mcmc_pars, filter, control = control)

When I run this, an error occurs:

“[\] [+++] ETA  ?s | 00:00:01 so far (  0%   0%   0%)Error: +++] ETA  ?s | 00:00:01 so far (  0%   0%   0%)Error: callr subproccess failed> object "dust_cpu_IDX_alloc" not found. " where IDX is my odin model script.

**Comment by richfitz** [comment]
I think the best way to cope with this is to register some hooks in dust itself that will recognise when the model it has is a transient package and arrange loading that package at the point of initialisation if it's not been done yet

**Comment by richfitz** [comment]
This turns out to be hard to via a dust hook through how R6 objects are serialised - the `parent_env` field ends up set as `.GlobalEnv` on load if the "package" is not already loaded. We can't force it to be loaded by name alone (even if we move it to the right place) without actually installing it (because `.packages()` and `loadNamespace` require that `Meta/package.rds` exists - quite possibly other things too.

I think that we might be able to do this by having dust models advertise that they need some help and provide information about paths, then arrange to provide hooks that can load the model as pieces of standalone code that we can then call from `mcstate::pmcmc_chains_run` on each of the sessions. Probably just passing an environment variable `MCSTATE_PACKAGE_PATH` might be enough?

**Comment by AVicco** [comment]
Dear Dr. RIch FitzJohn,

Thank you for your reply.

I have tried to follow your suggestion, by adding a MCSTATE_path to the
package, but this leads to a new error:




*mcstate_path <- "C:/Users/annav/Documents/R/win-library/4.1/mcstate"
pmcmc_chains_run(1, path = mcstate_path, n_threads = n_threads)
pmcmc_chains_run(2, path = mcstate_path, n_threads = n_threads)
pmcmc_chains_run(3, path = mcstate_path, n_threads = n_threads)*

*cannot open compressed file
'C:/Users/annav/Documents/R/win-library/4.1/mcstate/inputs.rds', probable
reason 'No such file or directory'*

I am not sure if I should create the inputs.rds file, and in this case what
should I write, so I am writing to ask you kindly if you could explain to
me in more detail what you mean by writing a link to the package and in
particular to which file.

Thank you in advance for your help.
Best wishes,
Anna Vicco

Il giorno ven 17 giu 2022 alle ore 12:12 Rich FitzJohn <
***@***.***> ha scritto:

**Comment by richfitz** [comment]
Sorry, these were notes to myself about how a fix might be implemented, not instructions for you! I'll look at this at some point over the next couple of weeks and will post with proper instructions once it works

**Comment by AVicco** [comment]
Thank you very much!

**Comment by AVicco** [comment]
Dear Dr. RIch FitzJohn,

I am sorry to bother you again, but - if you have time - I would have
another question/ problem regarding the package.

At the moment, following the instructions on the website (
https://mrc-ide.github.io/odin.dust/articles/sir_models.html), I am running
my model with a 4 times daily update (dt <- 0.25) and comparing the
estimated daily positive cases  with the reported daily incidence through
mcstate. The website suggests using a dt = 0.25 to increase the resolution,
but in my age-group model the update of compartment I (infectious) is
written as update(I[]) <- I[i] + n_S_I[i] - n_I_R[i], while the incidence
of positive cases given by the model (which I am comparing with the
reported incidence from the data) is defined as update(inc[]) <- n_S_I[i]).
Consequently, when I do an update 4 times a day, the model then saves and
uses (or at least this is what I have understood is doing) in the
comparison function only the last daily update, which works for I, but
creates a problem in the case of inc - where I lose the inputs of 3 out of
4 daily steps, as the equation does not take into account the individuals
already inside I. Therefore, the I compartment continues to rise, but the
inc does not mirror that increase. I hope my explanation is clear, but in
case I can write a basic model to simplify things and explain myself better.

Therefore, I am writing to kindly ask you if there is a way to solve this
potential problem by keeping a dt of 0.25, or if I have to use a dt of 1.
Also, in the sircovid model that you have desing, do you use a dt of 1 to
overcome this problem?

Thank you very much for your help.

Best regards,

Anna Vicco



Il giorno lun 27 giu 2022 alle ore 11:59 Anna Vicco ***@***.***>
ha scritto:

**Comment by richfitz** [comment]
Hi Anna - please don't add unrelated requests to an issue thread as it makes it hard to keep track of things.

It looks like you are at Imperial/DIDE - can you please send an email or Teams message to me. You will need to expand your question so that I can see more clearly what you are doing and trying to do without having to ask more questions. See the resources listed [here](https://mrc-ide.github.io/didehpc/articles/troubleshooting.html#asking-for-help) for advice on how to do this.
