### ISSUE TITLE
Inferring Parameters in an Age Structured Model

### ISSUE THREAD

**Issue by mshafq** [mrc-ide/mcstate#228]
I have an age-structured model in odin.dust that I would like to use with mcstate to infer parameters (all of which vary by age).

I've set up my model as outlined in the odin.dust vignette (https://mrc-ide.github.io/odin.dust/articles/sir_models.html#adding-age-structure-to-the-model), with each state and parameter as an array with dimensions number of age compartments (in this case, 2). I am able to run simulations on this model using dust with no issues.

However, I'm unable to figure out the correct way to set up pmcmc_parameter objects to describe the parameters that vary by age. Ideally, these should have different priors. I've tried a few different approaches, but none of them have worked thus far (see below, where beta is an age-varying parameter).

**Setting `initial` as a vector**
Code:
```
par <- list(beta = mcstate::pmcmc_parameter("beta", initial = c(0.2, 0.3), min = 0, max = 1))
```
Error: 
```
Error:` 'initial' must be a scalar
```

**Defining the parameter as a list of pmcmc_parameter objects**
Code: 
```
par <- list(beta = list(mcstate::pmcmc_parameter("beta", 0.2, min = 0, max = 1), mcstate::pmcmc_parameter("beta", 0.3, min = 0, max = 1)))
mcmc_pars <- mcstate::pmcmc_parameters$new(par, 0.1)
```
Error: 
```
Error in check_parameters(parameters, "pmcmc_parameter") : 
  Expected all elements of '...' to be 'pmcmc_parameter' objects
```

**Providing duplicate parameter names**
Code: 
```
par <- list(beta = mcstate::pmcmc_parameter("beta", 0.2, min = 0, max = 1), beta = mcstate::pmcmc_parameter("beta", 0.3, min = 0, max = 1))
mcmc_pars <- mcstate::pmcmc_parameters$new(par, 0.1)
```
Error: 
```
Error in check_parameters(parameters, "pmcmc_parameter") : 
  Duplicate parameter names: 'beta'
```

I would definitely appreciate any guidance on how best to set this up. Thank you!

**Comment by edknock** [comment]
Fitted parameters must be treated as scalar quantities, each of which should have a unique name. So e.g. you could name your two `beta` values `beta1` and `beta2`, which could then be setup as follows
```
par <- list(beta1 = mcstate::pmcmc_parameter("beta1", 0.2, min = 0, max = 1),
            beta2 = mcstate::pmcmc_parameter("beta2", 0.3, min = 0, max = 1))
```
and they can be given different prior distributions, e.g.
```
par <- list(beta1 = mcstate::pmcmc_parameter("beta1", 0.2, min = 0, max = 1,
                                             prior = function(x) dbeta(x, shape1 = 1.5, shape2 = 1.5, log = TRUE)),
            beta2 = mcstate::pmcmc_parameter("beta2", 0.3, min = 0, max = 1,
                                             prior = function(x) dbeta(x, shape1 = 1, shape2 = 3, log = TRUE)))
```

It might be that your dust model takes `beta` as a vector, in which case we need to make use of a transform function which maps your named vector of all fitted parameters `p` into a list of all parameters required by dust, e.g.
```
transform <- function(p) {
       list(beta = c(p$beta1, p$beta2))
}
mcmc_pars <- mcstate::pmcmc_parameters$new(par, proposal = diag(c(1, 1)), transform = transform)
```
For more explanation of using transform functions, see here: https://mrc-ide.github.io/mcstate/reference/pmcmc_parameters.html#parameter-transformations-1

**Comment by mshafq** [comment]
Thank you!

**Comment by whzhuscu** [comment]
Hello, this may be a stupid question, but when I read my model:
```
gen_sir <- odin.dust::odin_dust("sir.R")
```
 I do not know how to modify the following parameters, could you please provide some examples?
