### ISSUE TITLE
Add support for prediction based on a particle filter object?

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/mcstate#41]
Removed in 2967912ccf09dae111531a2c56cad6e721d5aa4a but perhaps useful in future? Do we ever need this?

**Comment by johnlees** [comment]
This is when you 'extend' a few example trajectories?

My memory is that this was more needed with the grid search, where you had to first sample the trajectories based on the posterior prob. The trajectories from the MCMC are already a sample of the posterior prob

**Comment by richfitz** [comment]
yeah, I confirmed with @edknock and @lwhittles that it was not actually needed, so rather than continuing to patch it I've ripped it out for now
